### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sloorush** [utreexo/utreexo#16]
Hey

I guess the work on the utreexo accumulator has shifted to this repository. I was wondering if I could continue work on documentation(https://github.com/mit-dci/utreexo/pull/324) over here?

Edit: The original issue: https://github.com/mit-dci/utreexo/issues/194

**Comment by kcalvinalvin** [comment]
Yeah that's fine. Though I'm trying to make is library a pure accumulator lib so the readme would be a bit different.

I can take a look if you make a PR.
